<a href="https://colab.research.google.com/github/sreesujit88/classification-in-KNN/blob/main/classification_in_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("Assignment-2_Data.csv")

Saving Assignment-2_Data.csv to Assignment-2_Data.csv


In [ ]:
print(df)

          Id    age           job   marital  education default  balance  \
0       1001  999.0    management   married   tertiary      no   2143.0   
1       1002   44.0    technician    single  secondary      no     29.0   
2       1003   33.0  entrepreneur   married  secondary      no      2.0   
3       1004   47.0   blue-collar   married    unknown      no   1506.0   
4       1005   33.0       unknown    single    unknown      no      1.0   
...      ...    ...           ...       ...        ...     ...      ...   
45206  46207   51.0    technician   married   tertiary      no    825.0   
45207  46208   71.0       retired  divorced    primary      no   1729.0   
45208  46209   72.0       retired   married  secondary      no   5715.0   
45209  46210   57.0   blue-collar   married  secondary      no    668.0   
45210  46211   37.0  entrepreneur   married  secondary      no   2971.0   

      housing loan    contact  day month  duration  campaign  pdays  previous  \
0         yes   no

In [ ]:
df.head

<bound method NDFrame.head of           Id    age           job   marital  education default  balance  \
0       1001  999.0    management   married   tertiary      no   2143.0   
1       1002   44.0    technician    single  secondary      no     29.0   
2       1003   33.0  entrepreneur   married  secondary      no      2.0   
3       1004   47.0   blue-collar   married    unknown      no   1506.0   
4       1005   33.0       unknown    single    unknown      no      1.0   
...      ...    ...           ...       ...        ...     ...      ...   
45206  46207   51.0    technician   married   tertiary      no    825.0   
45207  46208   71.0       retired  divorced    primary      no   1729.0   
45208  46209   72.0       retired   married  secondary      no   5715.0   
45209  46210   57.0   blue-collar   married  secondary      no    668.0   
45210  46211   37.0  entrepreneur   married  secondary      no   2971.0   

      housing loan    contact  day month  duration  campaign  pdays  

K-neighbor classifiers

In [ ]:
X = df.iloc[:,0:1].values
y = df.iloc[:, -1].values

In [ ]:
print(X)
print(y)

[[ 1001]
 [ 1002]
 [ 1003]
 ...
 [46209]
 [46210]
 [46211]]
['no' 'no' 'no' ... 'yes' 'no' 'no']


Train_test_split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = .33,random_state = 50)

In [ ]:
print(X_train)

[[19504]
 [13287]
 [ 7875]
 ...
 [43892]
 [39369]
 [15001]]


In [ ]:
print(X_test)

[[34956]
 [35905]
 [ 6548]
 ...
 [28869]
 [28832]
 [15079]]


In [ ]:
print(y_train)

['no' 'no' 'yes' ... 'yes' 'no' 'no']


In [ ]:
print(y_test)

['no' 'no' 'no' ... 'no' 'no' 'no']


Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

Fitting train set

In [ ]:
#from keras.models import load_model
#classifier = load_model('k Nearest Neighbors')
classifier = KNeighborsClassifier(n_neighbors = 1)
classifier.fit(X_train,y_train)


KNeighborsClassifier(n_neighbors=1)

predict test set

In [ ]:
y_pred = classifier.predict(X_test)

confusion matrix

In [ ]:
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test,y_pred, labels = df.target_unique())
df_cm = pd.DataFrame(cm, index = df.target_unique(), column = df.target_unique())

AttributeError: ignored

confusion matrix

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

In [ ]:
print(cm)

[[11914  1297]
 [ 1234   475]]


In [ ]:
score = classifier.score(X_train, y_train)

In [ ]:
print('Accuracy:', score)

Accuracy: 1.0
